name: DA360
channels:
  - pytorch
  - nvidia
  - xformers
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.9
  - cudatoolkit=11.8.0
  - pytorch::pytorch=2.1.1
  - pytorch::pytorch-cuda=11.8.0
  - pytorch::torchvision=0.16.1
  - xformers::xformers=0.0.23
  - matplotlib
  - tensorboard
  - scipy
  - opencv
  - tqdm
  - opt_einsum
  - imageio
  - scikit-image
  - p7zip
  - pip
  - pip:
    - gradio_imageslider
    - gradio==4.29.0

